# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
    ]
