# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Organization.Organization', verbose_name='机构'),
        ),
    ]
