# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Organization', verbose_name='机构'),
        ),
    ]
