# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_emailverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverify',
            name='add_time',
        ),
        migrations.AddField(
            model_name='emailverify',
            name='email',
            field=models.EmailField(default='default@qq.com', max_length=25, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
    ]
