# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180513_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverify',
            name='user',
        ),
    ]
