# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_emailverify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='code',
            field=models.CharField(default='123456', max_length=6, verbose_name='验证码'),
        ),
    ]
