# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20180603_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='123456', max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(default='default@qq.com', max_length=25, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '测试的',
                'verbose_name_plural': '测试的',
            },
        ),
    ]
