# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_ptestmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptestmodel',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')), 'verbose_name': '测试的', 'verbose_name_plural': '测试的'},
        ),
    ]
