# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20180610_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PTestModel',
        ),
    ]
